services:
    api:
        build: ./backend
        container_name: api-transporte
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - TZ=America/Sao_Paulo
        ports:
            - "8084:8080"
        networks:
            - otymus_net

    frontend:
        build: ./frontend
        container_name: frontend-transporte
        restart: unless-stopped
        environment:
            - TZ=America/Sao_Paulo
        ports:
            - "85:80"
        depends_on:
            - api
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "wget -qO- http://localhost/health >/dev/null 2>&1 || exit 1",
                ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 10s
        networks:
            - otymus_net

networks:
    otymus_net:
        external: true
