services:
    # ===========================
    # Backend - Spring Boot
    # ===========================
    api:
        build: ./backend
        container_name: api-transporte
        env_file:
            - .env
        ports:
            - "8084:8080"
        networks:
            - otymus_net

    # ===========================
    # Frontend - Angular + Nginx
    # ===========================
    frontend:
        build: ./frontend
        container_name: frontend-transporte
        ports:
            - "85:80"
        depends_on:
            - api
        networks:
            - otymus_net

networks:
    otymus_net:
        external: true
