services:
    # ===========================
    # Banco de Dados - MySql
    # ===========================
#    mysql:
#      image: mysql:8.0
#      container_name: mysql_nutran
#      environment:
#        MYSQL_DATABASE: db_nutran
#        MYSQL_ROOT_PASSWORD: root
#      ports:
#        - "3306:3306"
#      volumes:
#        - mysql_volume:/var/lib/mysql
#      networks: [ otymus_net ]
#      healthcheck:
#        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
#        interval: 5s
#        timeout: 3s
#        retries: 30

    # ===========================
    # Backend - Spring Boot
    # ===========================
    api:
        build: ./backend
        container_name: api-transporte
        restart: unless-stopped  # Reinicia sempre, exceto se você parar o container
        env_file:
            - .env
        ports:
          - "8084:8080"
        networks:
            - otymus_net

  # ===========================
    # Frontend - Angular + Nginx
    # ===========================
    frontend:
        build: ./frontend
        container_name: frontend-transporte
        restart: unless-stopped  # Reinicia sempre, exceto se você parar o container
        ports:
            - "85:80"
        depends_on:
            - api
        networks:
            - otymus_net


# ===========================
# Volumes (persistência)
# ===========================
volumes:
  mysql_volume:

# ===========================
# Redes
# ===========================
networks:
    otymus_net:
        external: true


