services:
  api:
    build: .
    container_name: api-transporte
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    networks:
      - otymus_net

networks:
  otymus_net:
    external: true
