CREATE DATABASE IF NOT EXISTS db_nutran
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'admin';

GRANT ALL PRIVILEGES ON db_nutran.* TO 'admin'@'%';

FLUSH PRIVILEGES;