CREATE TABLE tb_setor (
                          id BIGINT AUTO_INCREMENT PRIMARY KEY,
                          nome VARCHAR(255) NOT NULL UNIQUE
);

-- Dados iniciais
INSERT INTO tb_setor (nome) VALUES
                                ('HRG-NPDOC'),
                                ('HRG-NUPAC(LABORATORIO)'),
                                ('HRG-NRAD'),
                                ('HRG-NFH'),
                                ('HRG-NFC'),
                                ('HRG-NUAL'),
                                ('HRG-BANCO DE SANGUE'),
                                ('HRG-NARP'),
                                ('HRG-NSS'),
                                ('HRG-NÚCLEO DE TRANSPORTE'),
                                ('HRG-NÚCLEO DE BANCO DE LEITE'),
                                ('HRG-NVEPI (VIG. EPIDEMIOLÓGICA)'),
                                ('HRG-NUCAP (ANATOMIA)'),
                                ('HRG-NGPESP'),
                                ('HRG-NME'),
                                ('HRG-GERÊNCIA DE EMERGÊNCIA'),
                                ('HRG-GAMAD'),
                                ('HRG-TISIOLOGIA'),
                                ('HRG-NCIH'),
                                ('HRG-DIÁLISE'),
                                ('HRG-FISIOTERAPIA'),
                                ('HRG-OUVIDORIA'),
                                ('HRG-PSA'),
                                ('HRG-NHS'),
                                ('HRG-CENTRO CIRÚRGICO'),
                                ('SRSSU - SUPERINTENDÊNCIA'),
                                ('HRG-NSHMT'),
                                ('HRG-NEPS'),
                                ('HRG-CENTRO OBSTÉTRICO'),
                                ('HRG-NÚCLEO GESTÃO DE CUSTOS'),
                                ('HRG-CLÍNICA MÉDICA'),
                                ('HRG-NAGMP'),
                                ('HRG-TERAPIA OCUPACIONAL'),
                                ('HRG-PAV'),
                                ('HRG-GER. ENFERMAGEM'),
                                ('HRG-NECFM'),
                                ('HRG-ODONTOLOGIA'),
                                ('HRG-PAI'),
                                ('HRG-NÚCLEO DE RADIOLOGIA'),
                                ('HRG-CLÍNICA CIRÚRGICA'),
                                ('HRG-INTERNAÇÃO PEDIATRIA'),
                                ('HRG-POLICLÍNICA'),
                                ('HRG-NQSP'),
                                ('HRG-NCE'),
                                ('HRG-HEMODIALISE'),
                                ('HRG-DIRAPS'),
                                ('HRG-GAOESP'),
                                ('HRG-NTINF'),
                                ('HRG-NND');